### PR TITLE
Event Handling Callbacks

### PR DESCRIPTION
**Pull request by gemmadlou**
So when the iframe is loaded, opened or created, a callback can be connected via the constructor.

### CODE REVIEW

**Review by englishextra — COMMENTED** [review]
Two warnings
--
25 | 'options' is already defined. (remove var)
144 | Missing semicolon.

**Comment by englishextra** [comment]
@gemmadlou Thanks

**Comment by gemmadlou** [comment]
Thanks for merging that in @englishextra. That's awesome. And thanks for your code.

**Comment by englishextra** [comment]
@gemmadlou Likewise. I updated https://github.com/englishextra/iframe-lightbox/blob/master/iframe-lightbox.min.js

**Comment by gemmadlou** [comment]
Sorry for missing that

**Comment by englishextra** [comment]
@gemmadlou no worries

**Pull request merged**
